'use strict';

var model = {};
var initialized = false;

function init(sequelize) {
    delete module.exports.init; // Destroy itself to prevent repeated calls and clash with a model named 'init'.
    initialized = true;
    // Import model files and assign them to `model` object.
    model.AAATemp = sequelize.import('./definition/a-a-a-temp.js');
    model.AccessoryCategoryProductCategoryAccessoryType = sequelize.import('./definition/accessory-category-product-category-accessory-type.js');
    model.AccessoryCategoryType = sequelize.import('./definition/accessory-category-type.js');
    model.AccessoryCategoryTypeProductCategory = sequelize.import('./definition/accessory-category-type-product-category.js');
    model.AccessoryType = sequelize.import('./definition/accessory-type.js');
    model.ApplicationCondition = sequelize.import('./definition/application-condition.js');
    model.ApplicationContainer = sequelize.import('./definition/application-container.js');
    model.ApplicationContainerFee = sequelize.import('./definition/application-container-fee.js');
    model.ApplicationEquipmentProgramProductPricingLink = sequelize.import('./definition/application-equipment-program-product-pricing-link.js');
    model.ApplicationEquipmentSecurityAddressLink = sequelize.import('./definition/application-equipment-security-address-link.js');
    model.ApplicationHistory = sequelize.import('./definition/application-history.js');
    model.ApplicationHistoryPublicationType = sequelize.import('./definition/application-history-publication-type.js');
    model.ApplicationHistorySequenceView = sequelize.import('./definition/application-history-sequence-view.js');
    model.ApplicationHistoryType = sequelize.import('./definition/application-history-type.js');
    model.ApplicationHistoryTypeCategory = sequelize.import('./definition/application-history-type-category.js');
    model.ApplicationLVR = sequelize.import('./definition/application-l-v-r.js');
    model.ApplicationMotorProgramProductPricingLink = sequelize.import('./definition/application-motor-program-product-pricing-link.js');
    model.ApplicationMotorVehicleSecurityRegistrationState = sequelize.import('./definition/application-motor-vehicle-security-registration-state.js');
    model.ApplicationPartyRole = sequelize.import('./definition/application-party-role.js');
    model.ApplicationPartyRoleAncillary = sequelize.import('./definition/application-party-role-ancillary.js');
    model.ApplicationPartyRoleEmploymentContact = sequelize.import('./definition/application-party-role-employment-contacts.js');
    model.ApplicationPartyRoleHousehold = sequelize.import('./definition/application-party-role-household.js');
    model.ApplicationPartyRoleIdentity = sequelize.import('./definition/application-party-role-identity.js');
    model.ApplicationPartyRoleRelationship = sequelize.import('./definition/application-party-role-relationship.js');
    model.ApplicationPartyRoleRelationshipType = sequelize.import('./definition/application-party-role-relationship-type.js');
    model.ApplicationPartyRoleRelationshipTypePartyType = sequelize.import('./definition/application-party-role-relationship-type-party-type.js');
    model.ApplicationPartyRoleSequenceView = sequelize.import('./definition/application-party-role-sequence-view.js');
    model.ApplicationPartyRoleType = sequelize.import('./definition/application-party-role-type.js');
    model.ApplicationSecurity = sequelize.import('./definition/application-security.js');
    model.ApplicationSecurityOutgoingFinance = sequelize.import('./definition/application-security-outgoing-finance.js');
    model.ApplicationSecurityPurposeType = sequelize.import('./definition/application-security-purpose-type.js');
    model.ApplicationServiceabilityHistory = sequelize.import('./definition/application-serviceability-history.js');
    model.ApplicationServiceabilityHistoryValue = sequelize.import('./definition/application-serviceability-history-value.js');
    model.ApplicationStageType = sequelize.import('./definition/application-stage-type.js');
    model.ApplicationStageTypeApplicationStatusType = sequelize.import('./definition/application-stage-type-application-status-type.js');
    model.ApplicationStatusCategoryType = sequelize.import('./definition/application-status-category-type.js');
    model.ApplicationStatusHistory = sequelize.import('./definition/application-status-history.js');
    model.ApplicationStatusRollbackJobType = sequelize.import('./definition/application-status-rollback-job-type.js');
    model.ApplicationStatusTraxJob = sequelize.import('./definition/application-status-trax-job.js');
    model.ApplicationStatusType = sequelize.import('./definition/application-status-type.js');
    model.ApplicationStatusTypeProductCategory = sequelize.import('./definition/application-status-type-product-category.js');
    model.ApplicationStatusTypeProductCategoryCrashReasonType = sequelize.import('./definition/application-status-type-product-category-crash-reason-type.js');
    model.ApplicationStatusTypeProductCategoryLinkOrder = sequelize.import('./definition/application-status-type-product-category-link-order.js');
    model.ApplicationSupplierCrumbsPartyRole = sequelize.import('./definition/application-supplier-crumbs-party-role.js');
    model.ApplicationType = sequelize.import('./definition/application-type.js');
    model.ApplicationValuationOrderType = sequelize.import('./definition/application-valuation-order-type.js');
    model.Asset = sequelize.import('./definition/asset.js');
    model.AssetType = sequelize.import('./definition/asset-type.js');
    model.AutoAssessmentPolicyOwner = sequelize.import('./definition/auto-assessment-policy-owner.js');
    model.AutoAssessmentPolicyType = sequelize.import('./definition/auto-assessment-policy-type.js');
    model.AutoAssessmentProductCategoryPolicyTypeRuleType = sequelize.import('./definition/auto-assessment-product-category-policy-type-rule-type.js');
    model.AutoAssessmentRuleType = sequelize.import('./definition/auto-assessment-rule-type.js');
    model.AutoAssessmentRuleValue = sequelize.import('./definition/auto-assessment-rule-value.js');
    model.AutomatedValuationModelDetail = sequelize.import('./definition/automated-valuation-model-detail.js');
    model.ConditionAutoVerificationStatusType = sequelize.import('./definition/condition-auto-verification-status-type.js');
    model.ConditionCategoryType = sequelize.import('./definition/condition-category-type.js');
    model.ConditionDisplayType = sequelize.import('./definition/condition-display-type.js');
    model.ConditionLevelType = sequelize.import('./definition/condition-level-type.js');
    model.ConditionStageCategoryType = sequelize.import('./definition/condition-stage-category-type.js');
    model.ConditionType = sequelize.import('./definition/condition-type.js');
    model.ConditionTypeConfiguration = sequelize.import('./definition/condition-type-configuration.js');
    model.ConditionTypeConfigurationApplicationStatusType = sequelize.import('./definition/condition-type-configuration-application-status-type.js');
    model.ConditionTypeConfigurationRelationship = sequelize.import('./definition/condition-type-configuration-relationship.js');
    model.ConditionTypeConfigurationTraxJobType = sequelize.import('./definition/condition-type-configuration-trax-job-type.js');
    model.ConditionTypeProductCategory = sequelize.import('./definition/condition-type-product-category.js');
    model.ConditionTypeRelationshipType = sequelize.import('./definition/condition-type-relationship-type.js');
    model.ConditionTypeScannedDocumentAppliesToType = sequelize.import('./definition/condition-type-scanned-document-applies-to-type.js');
    model.ConditionVerificationRelationshipType = sequelize.import('./definition/condition-verification-relationship-type.js');
    model.ConditionVerificationStatusType = sequelize.import('./definition/condition-verification-status-type.js');
    model.CrashReasonType = sequelize.import('./definition/crash-reason-type.js');
    model.CreditCardAuthority = sequelize.import('./definition/credit-card-authority.js');
    model.CreditCardProcessHistory = sequelize.import('./definition/credit-card-process-history.js');
    model.CreditCardType = sequelize.import('./definition/credit-card-type.js');
    model.CreditReport = sequelize.import('./definition/credit-report.js');
    model.CreditReportAccount = sequelize.import('./definition/credit-report-account.js');
    model.CreditReportAddress = sequelize.import('./definition/credit-report-address.js');
    model.CreditReportAssociation = sequelize.import('./definition/credit-report-association.js');
    model.CreditReportBusinessName = sequelize.import('./definition/credit-report-business-name.js');
    model.CreditReportCourtAction = sequelize.import('./definition/credit-report-court-action.js');
    model.CreditReportCreditEnquiry = sequelize.import('./definition/credit-report-credit-enquiry.js');
    model.CreditReportDefault = sequelize.import('./definition/credit-report-default.js');
    model.CreditReportDirectorship = sequelize.import('./definition/credit-report-directorship.js');
    model.CreditReportDisqualifiedDirectorship = sequelize.import('./definition/credit-report-disqualified-directorship.js');
    model.CreditReportEmployment = sequelize.import('./definition/credit-report-employment.js');
    model.CreditReportFileNote = sequelize.import('./definition/credit-report-file-note.js');
    model.CreditReportIdentity = sequelize.import('./definition/credit-report-identity.js');
    model.CreditReportMain = sequelize.import('./definition/credit-report-main.js');
    model.CreditReportMessage = sequelize.import('./definition/credit-report-message.js');
    model.CreditReportPersonalInsolvency = sequelize.import('./definition/credit-report-personal-insolvency.js');
    model.CreditReportRepaymentHistory = sequelize.import('./definition/credit-report-repayment-history.js');
    model.CreditReportRequired = sequelize.import('./definition/credit-report-required.js');
    model.CreditReportRequiredSequenceView = sequelize.import('./definition/credit-report-required-sequence-view.js');
    model.CreditReportScoreDataContributingFactor = sequelize.import('./definition/credit-report-score-data-contributing-factor.js');
    model.CreditReportSummaryDatum = sequelize.import('./definition/credit-report-summary-data.js');
    model.CreditReportType = sequelize.import('./definition/credit-report-type.js');
    model.CrumbsAddress = sequelize.import('./definition/crumbs--address.js');
    model.CrumbsAddresssequenceview = sequelize.import('./definition/crumbs--address-sequence-view.js');
    model.CrumbsAddresstype = sequelize.import('./definition/crumbs--address-type.js');
    model.CrumbsAlignmenttype = sequelize.import('./definition/crumbs--alignment-type.js');
    model.CrumbsApplicationrole = sequelize.import('./definition/crumbs--application-role.js');
    model.CrumbsBankaccount = sequelize.import('./definition/crumbs--bank-account.js');
    model.CrumbsBankbsb = sequelize.import('./definition/crumbs--bank-b-s-b.js');
    model.CrumbsBankbsbsequenceview = sequelize.import('./definition/crumbs--bank-b-s-b-sequence-view.js');
    model.CrumbsBrand = sequelize.import('./definition/crumbs--brand.js');
    model.CrumbsBrandtext = sequelize.import('./definition/crumbs--brand-text.js');
    model.CrumbsBrokerprogramagreement = sequelize.import('./definition/crumbs--broker-program-agreement.js');
    model.CrumbsClaimtype = sequelize.import('./definition/crumbs--claim-type.js');
    model.CrumbsClaimvalue = sequelize.import('./definition/crumbs--claim-value.js');
    model.CrumbsCompany = sequelize.import('./definition/crumbs--company.js');
    model.CrumbsCompanynamebypartyrole = sequelize.import('./definition/crumbs--company-name-by-party-role.js');
    model.CrumbsCompanytype = sequelize.import('./definition/crumbs--company-type.js');
    model.CrumbsCountry = sequelize.import('./definition/crumbs--country.js');
    model.CrumbsCurrencytype = sequelize.import('./definition/crumbs--currency-type.js');
    model.CrumbsDocumentlocationtype = sequelize.import('./definition/crumbs--document-location-type.js');
    model.CrumbsEmailaddress = sequelize.import('./definition/crumbs--email-address.js');
    model.CrumbsEmailaddresssequenceview = sequelize.import('./definition/crumbs--email-address-sequence-view.js');
    model.CrumbsEquipmentfinanceloanapplication = sequelize.import('./definition/crumbs--equipment-finance-loan-application.js');
    model.CrumbsFirstmaccreditscorehistory = sequelize.import('./definition/crumbs--firstmac-credit-score-history.js');
    model.CrumbsFirstmaccreditscoretype = sequelize.import('./definition/crumbs--firstmac-credit-score-type.js');
    model.CrumbsGendertype = sequelize.import('./definition/crumbs--gender-type.js');
    model.CrumbsIndustrytype = sequelize.import('./definition/crumbs--industry-type.js');
    model.CrumbsLocationtype = sequelize.import('./definition/crumbs--location-type.js');
    model.CrumbsLogin = sequelize.import('./definition/crumbs--login.js');
    model.CrumbsLoginclaimvalueclaimtype = sequelize.import('./definition/crumbs--login-claim-value-claim-type.js');
    model.CrumbsMaritalstatustype = sequelize.import('./definition/crumbs--marital-status-type.js');
    model.CrumbsMotorvehicleloanapplication = sequelize.import('./definition/crumbs--motor-vehicle-loan-application.js');
    model.CrumbsObjectcolourtype = sequelize.import('./definition/crumbs--object-colour-type.js');
    model.CrumbsParty = sequelize.import('./definition/crumbs--party.js');
    model.CrumbsPartyaddress = sequelize.import('./definition/crumbs--party-address.js');
    model.CrumbsPartyaddresssequenceview = sequelize.import('./definition/crumbs--party-address-sequence-view.js');
    model.CrumbsPartybankaccount = sequelize.import('./definition/crumbs--party-bank-account.js');
    model.CrumbsPartybankaccounttype = sequelize.import('./definition/crumbs--party-bank-account-type.js');
    model.CrumbsPartycompliance = sequelize.import('./definition/crumbs--party-compliance.js');
    model.CrumbsPartyemail = sequelize.import('./definition/crumbs--party-email.js');
    model.CrumbsPartyemailsequenceview = sequelize.import('./definition/crumbs--party-email-sequence-view.js');
    model.CrumbsPartynamebypartyroleid = sequelize.import('./definition/crumbs--party-name-by-party-role-i-d.js');
    model.CrumbsPartyrole = sequelize.import('./definition/crumbs--party-role.js');
    model.CrumbsPartyrolerelationship = sequelize.import('./definition/crumbs--party-role-relationship.js');
    model.CrumbsPartyrolesequenceview = sequelize.import('./definition/crumbs--party-role-sequence-view.js');
    model.CrumbsPartyrolesuite = sequelize.import('./definition/crumbs--party-role-suite.js');
    model.CrumbsPartyroletype = sequelize.import('./definition/crumbs--party-role-type.js');
    model.CrumbsPartyscorehistory = sequelize.import('./definition/crumbs--party-score-history.js');
    model.CrumbsPartyscorehistorysequenceview = sequelize.import('./definition/crumbs--party-score-history-sequence-view.js');
    model.CrumbsPartysequenceview = sequelize.import('./definition/crumbs--party-sequence-view.js');
    model.CrumbsPartytelephone = sequelize.import('./definition/crumbs--party-telephone.js');
    model.CrumbsPartytelephonesequenceview = sequelize.import('./definition/crumbs--party-telephone-sequence-view.js');
    model.CrumbsPartytrustee = sequelize.import('./definition/crumbs--party-trustee.js');
    model.CrumbsPartytype = sequelize.import('./definition/crumbs--party-type.js');
    model.CrumbsPermissiontype = sequelize.import('./definition/crumbs--permission-type.js');
    model.CrumbsPerson = sequelize.import('./definition/crumbs--person.js');
    model.CrumbsResidencytype = sequelize.import('./definition/crumbs--residency-type.js');
    model.CrumbsRoletype = sequelize.import('./definition/crumbs--role-type.js');
    model.CrumbsRoletypepermissiontype = sequelize.import('./definition/crumbs--role-type-permission-type.js');
    model.CrumbsSalutationtype = sequelize.import('./definition/crumbs--salutation-type.js');
    model.CrumbsState = sequelize.import('./definition/crumbs--state.js');
    model.CrumbsStreettype = sequelize.import('./definition/crumbs--street-type.js');
    model.CrumbsSuburb = sequelize.import('./definition/crumbs--suburb.js');
    model.CrumbsSupplierpartyroletyperelationship = sequelize.import('./definition/crumbs--supplier-party-role-type-relationship.js');
    model.CrumbsTelephonenumber = sequelize.import('./definition/crumbs--telephone-number.js');
    model.CrumbsTelephonenumbersequenceview = sequelize.import('./definition/crumbs--telephone-number-sequence-view.js');
    model.CrumbsTelephonetype = sequelize.import('./definition/crumbs--telephone-type.js');
    model.CrumbsTrust = sequelize.import('./definition/crumbs--trust.js');
    model.CrumbsTrustpurposetype = sequelize.import('./definition/crumbs--trust-purpose-type.js');
    model.CrumbsTruststructuretype = sequelize.import('./definition/crumbs--trust-structure-type.js');
    model.CurrencyType = sequelize.import('./definition/currency-type.js');
    model.Deposit = sequelize.import('./definition/deposit.js');
    model.DepositType = sequelize.import('./definition/deposit-type.js');
    model.DirectDebit = sequelize.import('./definition/direct-debit.js');
    model.Disbursement = sequelize.import('./definition/disbursement.js');
    model.DisbursementDrawHistory = sequelize.import('./definition/disbursement-draw-history.js');
    model.DisbursementPaymentType = sequelize.import('./definition/disbursement-payment-type.js');
    model.DisbursementSubType = sequelize.import('./definition/disbursement-sub-type.js');
    model.DisbursementType = sequelize.import('./definition/disbursement-type.js');
    model.DisbursementTypeSubTypeOption = sequelize.import('./definition/disbursement-type-sub-type-option.js');
    model.DocumentationType = sequelize.import('./definition/documentation-type.js');
    model.DocumentcontrolDocumenttype = sequelize.import('./definition/documentcontrol--document-type.js');
    model.DocumentcontrolGeneration = sequelize.import('./definition/documentcontrol--generation.js');
    model.DocumentcontrolGenerationset = sequelize.import('./definition/documentcontrol--generation-set.js');
    model.DocumentcontrolGenerationsetitem = sequelize.import('./definition/documentcontrol--generation-set-item.js');
    model.DocumentcontrolTemplate = sequelize.import('./definition/documentcontrol--template.js');
    model.DocumentOrderHistory = sequelize.import('./definition/document-order-history.js');
    model.DocumentOrderHistoryApplicationPartyRole = sequelize.import('./definition/document-order-history-application-party-role.js');
    model.DocumentOrderHistoryApplicationPartyRoleStatus = sequelize.import('./definition/document-order-history-application-party-role-status.js');
    model.DocumentOrderHistoryApplicationPartyRoleViewer = sequelize.import('./definition/document-order-history-application-party-role-viewer.js');
    model.DocumentOrderHistoryAuditEvent = sequelize.import('./definition/document-order-history-audit-event.js');
    model.DocumentOrderHistoryAuditEventDatum = sequelize.import('./definition/document-order-history-audit-event-data.js');
    model.DocumentOrderHistoryAuditKeyType = sequelize.import('./definition/document-order-history-audit-key-type.js');
    model.DocumentOrderStatusCategory = sequelize.import('./definition/document-order-status-category.js');
    model.DocumentOrderStatusHistory = sequelize.import('./definition/document-order-status-history.js');
    model.DocumentOrderStatusType = sequelize.import('./definition/document-order-status-type.js');
    model.DocumentPackRuleType = sequelize.import('./definition/document-pack-rule-type.js');
    model.Employment = sequelize.import('./definition/employment.js');
    model.EmploymentBasisType = sequelize.import('./definition/employment-basis-type.js');
    model.EmploymentCategoryType = sequelize.import('./definition/employment-category-type.js');
    model.EmploymentStatusType = sequelize.import('./definition/employment-status-type.js');
    model.EmploymentStatusTypeBasisTypeRelationship = sequelize.import('./definition/employment-status-type-basis-type-relationship.js');
    model.EquipmentFinanceLoanApplication = sequelize.import('./definition/equipment-finance-loan-application.js');
    model.EquipmentFinanceLoanApplicationInvoice = sequelize.import('./definition/equipment-finance-loan-application-invoice.js');
    model.EquipmentFinanceSecurity = sequelize.import('./definition/equipment-finance-security.js');
    model.EquipmentFinanceSecuritySerialLocation = sequelize.import('./definition/equipment-finance-security-serial-location.js');
    model.EquipmentFinanceSecurityType = sequelize.import('./definition/equipment-finance-security-type.js');
    model.FeeType = sequelize.import('./definition/fee-type.js');
    model.FeeTypeProductCategory = sequelize.import('./definition/fee-type-product-category.js');
    model.FinalApprovalProcessHistory = sequelize.import('./definition/final-approval-process-history.js');
    model.FinalApprovalProcessProductCategoryJobType = sequelize.import('./definition/final-approval-process-product-category-job-type.js');
    model.FinalApprovalProcessType = sequelize.import('./definition/final-approval-process-type.js');
    model.FinalApprovalProcessTypeProductCategoryType = sequelize.import('./definition/final-approval-process-type-product-category-type.js');
    model.FrequencyType = sequelize.import('./definition/frequency-type.js');
    model.HomeLoanApplication = sequelize.import('./definition/home-loan-application.js');
    model.HomeLoanApplicationAdditional = sequelize.import('./definition/home-loan-application-additional.js');
    model.HomeLoanApplicationRepaymentTransfer = sequelize.import('./definition/home-loan-application-repayment-transfer.js');
    model.HomeLoanSecurity = sequelize.import('./definition/home-loan-security.js');
    model.HomeLoanSecurityType = sequelize.import('./definition/home-loan-security-type.js');
    model.Household = sequelize.import('./definition/household.js');
    model.Income = sequelize.import('./definition/income.js');
    model.IncomeAdditional = sequelize.import('./definition/income-additional.js');
    model.IncomeAdditionalType = sequelize.import('./definition/income-additional-type.js');
    model.IncomeEmployment = sequelize.import('./definition/income-employment.js');
    model.IncomeSourceType = sequelize.import('./definition/income-source-type.js');
    model.Insurance = sequelize.import('./definition/insurance.js');
    model.InsuranceType = sequelize.import('./definition/insurance-type.js');
    model.InsuranceTypeProductCategory = sequelize.import('./definition/insurance-type-product-category.js');
    model.Invoice = sequelize.import('./definition/invoice.js');
    model.Liability = sequelize.import('./definition/liability.js');
    model.LiabilityCategoryType = sequelize.import('./definition/liability-category-type.js');
    model.LiabilityType = sequelize.import('./definition/liability-type.js');
    model.LiteHistoryImportTemp = sequelize.import('./definition/lite-history-import--temp.js');
    model.Loan = sequelize.import('./definition/loan.js');
    model.LoanMarginHistory = sequelize.import('./definition/loan-margin-history.js');
    model.LoanMDRHistory = sequelize.import('./definition/loan-m-d-r-history.js');
    model.LoanProgramProductHistory = sequelize.import('./definition/loan-program-product-history.js');
    model.LoanPurpose = sequelize.import('./definition/loan-purpose.js');
    model.LoanPurposeGroup = sequelize.import('./definition/loan-purpose-group.js');
    model.LoanPurposeType = sequelize.import('./definition/loan-purpose-type.js');
    model.LoanPurposeTypeProductCategory = sequelize.import('./definition/loan-purpose-type-product-category.js');
    model.LoanPurposeTypeTraxJobType = sequelize.import('./definition/loan-purpose-type-trax-job-type.js');
    model.LoanTrackerActionType = sequelize.import('./definition/loan-tracker-action-type.js');
    model.LoanTrackerApplicationStatusAllowableDocument = sequelize.import('./definition/loan-tracker-application-status-allowable-documents.js');
    model.LoanTrackerConditionDisplayType = sequelize.import('./definition/loan-tracker-condition-display-type.js');
    model.LoanTrackerConditionVerificationStage = sequelize.import('./definition/loan-tracker-condition-verification-stage.js');
    model.LoanTrackerDocumentRequirementType = sequelize.import('./definition/loan-tracker-document-requirement-type.js');
    model.LoanTrackerDocumentUploadType = sequelize.import('./definition/loan-tracker-document-upload-type.js');
    model.LoanTrackerForm = sequelize.import('./definition/loan-tracker-form.js');
    model.LoanTrackerToolTip = sequelize.import('./definition/loan-tracker-tool-tip.js');
    model.LoanTrackerToolTipType = sequelize.import('./definition/loan-tracker-tool-tip-type.js');
    model.LoanXrefHistory = sequelize.import('./definition/loan-xref-history.js');
    model.LoanXrefPoolHistory = sequelize.import('./definition/loan-xref-pool-history.js');
    model.LoanXrefPoolHistoryStatus = sequelize.import('./definition/loan-xref-pool-history-status.js');
    model.LoanXrefPoolHistoryStatusLevelType = sequelize.import('./definition/loan-xref-pool-history-status-level-type.js');
    model.LoanXrefPoolHistoryStatusType = sequelize.import('./definition/loan-xref-pool-history-status-type.js');
    model.LoanXrefValue = sequelize.import('./definition/loan-xref-value.js');
    model.LoanXrefValueType = sequelize.import('./definition/loan-xref-value-type.js');
    model.LotType = sequelize.import('./definition/lot-type.js');
    model.MaritalStatusType = sequelize.import('./definition/marital-status-type.js');
    model.MortgageType = sequelize.import('./definition/mortgage-type.js');
    model.Mortgagor = sequelize.import('./definition/mortgagor.js');
    model.MotorVehicleLoanApplication = sequelize.import('./definition/motor-vehicle-loan-application.js');
    model.MotorVehicleLoanApplicationInvoice = sequelize.import('./definition/motor-vehicle-loan-application-invoice.js');
    model.MotorVehicleRateAdjustmentHistory = sequelize.import('./definition/motor-vehicle-rate-adjustment-history.js');
    model.MotorVehicleSecurity = sequelize.import('./definition/motor-vehicle-security.js');
    model.MotorVehicleSecurityType = sequelize.import('./definition/motor-vehicle-security-type.js');
    model.MotorVehicleSecurityValuation = sequelize.import('./definition/motor-vehicle-security-valuation.js');
    model.OccupancyType = sequelize.import('./definition/occupancy-type.js');
    model.PartyRole = sequelize.import('./definition/party-role.js');
    model.PartyRoleSequenceView = sequelize.import('./definition/party-role-sequence-view.js');
    model.PersonalLoanApplication = sequelize.import('./definition/personal-loan-application.js');
    model.PmsBalloon = sequelize.import('./definition/pms--balloon.js');
    model.PmsEquipmentfinanceloanproduct = sequelize.import('./definition/pms--equipment-finance-loan-product.js');
    model.PmsEquipmentfinanceloanprogramproductpricing = sequelize.import('./definition/pms--equipment-finance-loan-program-product-pricing.js');
    model.PmsEquipmentfinanceproductcategory = sequelize.import('./definition/pms--equipment-finance-product-category.js');
    model.PmsEquipmentfinanceproducttypefrequencytype = sequelize.import('./definition/pms--equipment-finance-product-type-frequency-type.js');
    model.PmsFrequencytype = sequelize.import('./definition/pms--frequency-type.js');
    model.PmsFunderproduct = sequelize.import('./definition/pms--funder-product.js');
    model.PmsFunderproductcosthistory = sequelize.import('./definition/pms--funder-product-cost-history.js');
    model.PmsInteresttype = sequelize.import('./definition/pms--interest-type.js');
    model.PmsMotorvehicleloanproduct = sequelize.import('./definition/pms--motor-vehicle-loan-product.js');
    model.PmsMotorvehicleloanprogramproductpricing = sequelize.import('./definition/pms--motor-vehicle-loan-program-product-pricing.js');
    model.PmsProduct = sequelize.import('./definition/pms--product.js');
    model.PmsProgramproduct = sequelize.import('./definition/pms--program-product.js');
    model.PmsProgramproductinformationByprogramproductpricingid = sequelize.import('./definition/pms--program-product-information--by-program-product-pricing-i-d.js');
    model.PmsTermtype = sequelize.import('./definition/pms--term-type.js');
    model.Pool = sequelize.import('./definition/pool.js');
    model.PPSRStatusType = sequelize.import('./definition/p-p-s-r-status-type.js');
    model.PremisesLocationType = sequelize.import('./definition/premises-location-type.js');
    model.ProductCategory = sequelize.import('./definition/product-category.js');
    model.ProductContainer = sequelize.import('./definition/product-container.js');
    model.Quote = sequelize.import('./definition/quote.js');
    model.QuoteType = sequelize.import('./definition/quote-type.js');
    model.RateAdjustmentReasonType = sequelize.import('./definition/rate-adjustment-reason-type.js');
    model.RepaymentAmountType = sequelize.import('./definition/repayment-amount-type.js');
    model.RepaymentMethodType = sequelize.import('./definition/repayment-method-type.js');
    model.ResidencyType = sequelize.import('./definition/residency-type.js');
    model.RetailCustomer = sequelize.import('./definition/retail--customer.js');
    model.RetailEquipmentfinanceloanapplication = sequelize.import('./definition/retail--equipment-finance-loan-application.js');
    model.RetailLead = sequelize.import('./definition/retail--lead.js');
    model.RetailLeadcreationsource = sequelize.import('./definition/retail--lead-creation-source.js');
    model.RetailLeadcustomerrelationship = sequelize.import('./definition/retail--lead-customer-relationship.js');
    model.RetailLeadhistory = sequelize.import('./definition/retail--lead-history.js');
    model.RetailMotorvehicleenginetype = sequelize.import('./definition/retail--motor-vehicle-engine-type.js');
    model.RetailMotorvehicleloanapplication = sequelize.import('./definition/retail--motor-vehicle-loan-application.js');
    model.RetailMotorvehiclemake = sequelize.import('./definition/retail--motor-vehicle-make.js');
    model.RetailMotorvehiclemodel = sequelize.import('./definition/retail--motor-vehicle-model.js');
    model.RetailMotorvehiclespecification = sequelize.import('./definition/retail--motor-vehicle-specification.js');
    model.RiskDescriptionType = sequelize.import('./definition/risk-description-type.js');
    model.RiskRatingType = sequelize.import('./definition/risk-rating-type.js');
    model.RiskType = sequelize.import('./definition/risk-type.js');
    model.Security = sequelize.import('./definition/security.js');
    model.SecurityAccessory = sequelize.import('./definition/security-accessory.js');
    model.SecurityEncumbranceType = sequelize.import('./definition/security-encumbrance-type.js');
    model.SecurityMortgageRegistration = sequelize.import('./definition/security-mortgage-registration.js');
    model.SecurityPPSR = sequelize.import('./definition/security-p-p-s-r.js');
    model.SecuritySerialLocation = sequelize.import('./definition/security-serial-location.js');
    model.SecurityStatusType = sequelize.import('./definition/security-status-type.js');
    model.SecurityTitleDealingType = sequelize.import('./definition/security-title-dealing-type.js');
    model.SecurityTitleEncumbrance = sequelize.import('./definition/security-title-encumbrances.js');
    model.SecurityTitleInsurance = sequelize.import('./definition/security-title-insurance.js');
    model.SecurityTitlePlanType = sequelize.import('./definition/security-title-plan-type.js');
    model.SecurityTitleType = sequelize.import('./definition/security-title-type.js');
    model.SecurityType = sequelize.import('./definition/security-type.js');
    model.ServiceabilityCalculatorVersion = sequelize.import('./definition/serviceability-calculator-version.js');
    model.ServiceabilityHistory = sequelize.import('./definition/serviceability-history.js');
    model.ServiceabilityValueHistory = sequelize.import('./definition/serviceability-value-history.js');
    model.ServiceabilityValueType = sequelize.import('./definition/serviceability-value-type.js');
    model.Settlement = sequelize.import('./definition/settlement.js');
    model.SettlementCategoryType = sequelize.import('./definition/settlement-category-type.js');
    model.SettlementCheckpoint = sequelize.import('./definition/settlement-checkpoint.js');
    model.SettlementCheckpointIllegalCurrent = sequelize.import('./definition/settlement-checkpoint-illegal-current.js');
    model.SettlementCheckpointRequiredBefore = sequelize.import('./definition/settlement-checkpoint-required-before.js');
    model.SettlementCheckpointType = sequelize.import('./definition/settlement-checkpoint-type.js');
    model.SettlementProcessHistory = sequelize.import('./definition/settlement-process-history.js');
    model.SettlementProcessHistorySettlement = sequelize.import('./definition/settlement-process-history-settlements.js');
    model.SettlementProcessType = sequelize.import('./definition/settlement-process-type.js');
    model.SettlementType = sequelize.import('./definition/settlement-type.js');
    model.SettlementTypeCategoryTypeOption = sequelize.import('./definition/settlement-type-category-type-option.js');
    model.SubConditionLevelType = sequelize.import('./definition/sub-condition-level-type.js');
    model.SubmissionSourceType = sequelize.import('./definition/submission-source-type.js');
    model.TermCategory = sequelize.import('./definition/term-category.js');
    model.TermType = sequelize.import('./definition/term-type.js');
    model.TestAppSubmission = sequelize.import('./definition/test-app-submission.js');
    model.TradingHistoryAggregatedPaymentReference = sequelize.import('./definition/trading-history-aggregated-payment-reference.js');
    model.TradingHistoryAnnualReturn = sequelize.import('./definition/trading-history-annual-returns.js');
    model.TradingHistoryASICDocument = sequelize.import('./definition/trading-history-a-s-i-c-documents.js');
    model.TradingHistoryBrokerAgentEnquiry = sequelize.import('./definition/trading-history-broker-agent-enquiries.js');
    model.TradingHistoryClassification = sequelize.import('./definition/trading-history-classification.js');
    model.TradingHistoryCompanyDirectorAddress = sequelize.import('./definition/trading-history-company-director-address.js');
    model.TradingHistoryCompanyDirectorEmployment = sequelize.import('./definition/trading-history-company-director-employment.js');
    model.TradingHistoryCompanyDirector = sequelize.import('./definition/trading-history-company-directors.js');
    model.TradingHistoryCourtJudgement = sequelize.import('./definition/trading-history-court-judgements.js');
    model.TradingHistoryCourtWrit = sequelize.import('./definition/trading-history-court-writs.js');
    model.TradingHistoryCreditEnquiry = sequelize.import('./definition/trading-history-credit-enquiries.js');
    model.TradingHistoryCurrentCompanyAddress = sequelize.import('./definition/trading-history-current-company-addresses.js');
    model.TradingHistoryCurrentCompanyShare = sequelize.import('./definition/trading-history-current-company-shares.js');
    model.TradingHistoryDeductibleGiftRecipient = sequelize.import('./definition/trading-history-deductible-gift-recipients.js');
    model.TradingHistoryDFAddress = sequelize.import('./definition/trading-history-d-f-address.js');
    model.TradingHistoryDirectorBankruptcy = sequelize.import('./definition/trading-history-director-bankruptcies.js');
    model.TradingHistoryDirectorBrokerAgentEnquiry = sequelize.import('./definition/trading-history-director-broker-agent-enquiries.js');
    model.TradingHistoryDirectorCourtJudgement = sequelize.import('./definition/trading-history-director-court-judgements.js');
    model.TradingHistoryDirectorCourtWrit = sequelize.import('./definition/trading-history-director-court-writs.js');
    model.TradingHistoryDirectorCreditEnquiry = sequelize.import('./definition/trading-history-director-credit-enquiries.js');
    model.TradingHistoryDirectorCreditProvider = sequelize.import('./definition/trading-history-director-credit-providers.js');
    model.TradingHistoryDirectorCrossReference = sequelize.import('./definition/trading-history-director-cross-references.js');
    model.TradingHistoryDirectorDirectorshipMessage = sequelize.import('./definition/trading-history-director-directorship-messages.js');
    model.TradingHistoryDirectorDirectorship = sequelize.import('./definition/trading-history-director-directorships.js');
    model.TradingHistoryDirectorDisqualificationMessage = sequelize.import('./definition/trading-history-director-disqualification-messages.js');
    model.TradingHistoryDirectorDisqualification = sequelize.import('./definition/trading-history-director-disqualifications.js');
    model.TradingHistoryDirectorFault = sequelize.import('./definition/trading-history-director-faults.js');
    model.TradingHistoryDirectorFileNote = sequelize.import('./definition/trading-history-director-file-notes.js');
    model.TradingHistoryDirectorLegalMessage = sequelize.import('./definition/trading-history-director-legal-messages.js');
    model.TradingHistoryDirectorPaymentDefault = sequelize.import('./definition/trading-history-director-payment-defaults.js');
    model.TradingHistoryDirectorProprietorshipMessage = sequelize.import('./definition/trading-history-director-proprietorship-messages.js');
    model.TradingHistoryDirectorProprietorship = sequelize.import('./definition/trading-history-director-proprietorships.js');
    model.TradingHistoryDirector = sequelize.import('./definition/trading-history-directors.js');
    model.TradingHistoryDirectorScore = sequelize.import('./definition/trading-history-director-score.js');
    model.TradingHistoryDirectorScoreContributingFactor = sequelize.import('./definition/trading-history-director-score-contributing-factors.js');
    model.TradingHistoryDirectorScoreError = sequelize.import('./definition/trading-history-director-score-errors.js');
    model.TradingHistoryDirectorScoreWarning = sequelize.import('./definition/trading-history-director-score-warnings.js');
    model.TradingHistoryDirectorSummaryEntry = sequelize.import('./definition/trading-history-director-summary-entries.js');
    model.TradingHistoryDirectorWarningMetaDatum = sequelize.import('./definition/trading-history-director-warning-meta-data.js');
    model.TradingHistoryDirectorWarning = sequelize.import('./definition/trading-history-director-warnings.js');
    model.TradingHistoryError = sequelize.import('./definition/trading-history-errors.js');
    model.TradingHistoryExternalAdministrator = sequelize.import('./definition/trading-history-external-administrators.js');
    model.TradingHistoryFileNote = sequelize.import('./definition/trading-history-file-notes.js');
    model.TradingHistoryFinancialReport = sequelize.import('./definition/trading-history-financial-reports.js');
    model.TradingHistoryFutureCompanyAddress = sequelize.import('./definition/trading-history-future-company-addresses.js');
    model.TradingHistoryIndividualShareHolder = sequelize.import('./definition/trading-history-individual-share-holders.js');
    model.TradingHistoryIndustryDaysBeyondTerm = sequelize.import('./definition/trading-history-industry-days-beyond-term.js');
    model.TradingHistoryIndustryLatePaymentDay = sequelize.import('./definition/trading-history-industry-late-payment-days.js');
    model.TradingHistoryIndustryScore = sequelize.import('./definition/trading-history-industry-scores.js');
    model.TradingHistoryIndustryScoreYPoint = sequelize.import('./definition/trading-history-industry-score-y-points.js');
    model.TradingHistoryLast200PaymentReference = sequelize.import('./definition/trading-history-last200-payment-reference.js');
    model.TradingHistoryLegalMessage = sequelize.import('./definition/trading-history-legal-messages.js');
    model.TradingHistoryMain = sequelize.import('./definition/trading-history-main.js');
    model.TradingHistoryMarketLatePaymentDay = sequelize.import('./definition/trading-history-market-late-payment-days.js');
    model.TradingHistoryMercantileEnquiry = sequelize.import('./definition/trading-history-mercantile-enquiries.js');
    model.TradingHistoryOrganisationDetail = sequelize.import('./definition/trading-history-organisation-details.js');
    model.TradingHistoryOrganisationShareHolder = sequelize.import('./definition/trading-history-organisation-share-holders.js');
    model.TradingHistoryOtherEntity = sequelize.import('./definition/trading-history-other-entities.js');
    model.TradingHistoryOtherOfficer = sequelize.import('./definition/trading-history-other-officers.js');
    model.TradingHistoryOtherOrganisationOfficer = sequelize.import('./definition/trading-history-other-organisation-officers.js');
    model.TradingHistoryPaymentDefault = sequelize.import('./definition/trading-history-payment-defaults.js');
    model.TradingHistoryPaymentReferencesByDebtSize = sequelize.import('./definition/trading-history-payment-references-by-debt-size.js');
    model.TradingHistoryPaymentSummary = sequelize.import('./definition/trading-history-payment-summary.js');
    model.TradingHistoryPetition = sequelize.import('./definition/trading-history-petitions.js');
    model.TradingHistoryPPSRCommercialCollateralClassSummary = sequelize.import('./definition/trading-history-p-p-s-r-commercial-collateral-class-summary.js');
    model.TradingHistoryPPSRRegistrationChange = sequelize.import('./definition/trading-history-p-p-s-r-registration-changes.js');
    model.TradingHistoryPPSRRegistrationCollateral = sequelize.import('./definition/trading-history-p-p-s-r-registration-collateral.js');
    model.TradingHistoryPPSRRegistrationCollateralAttachment = sequelize.import('./definition/trading-history-p-p-s-r-registration-collateral-attachments.js');
    model.TradingHistoryPPSRRegistrationDetail = sequelize.import('./definition/trading-history-p-p-s-r-registration-details.js');
    model.TradingHistoryPPSRRegistrationDetailSecuredParty = sequelize.import('./definition/trading-history-p-p-s-r-registration-detail-secured-parties.js');
    model.TradingHistoryPPSRRegistrationElement = sequelize.import('./definition/trading-history-p-p-s-r-registration-elements.js');
    model.TradingHistoryPPSRRegistrationElementSecuredParty = sequelize.import('./definition/trading-history-p-p-s-r-registration-element-secured-parties.js');
    model.TradingHistoryPPSRRegistrationGrantor = sequelize.import('./definition/trading-history-p-p-s-r-registration-grantors.js');
    model.TradingHistoryPPSRRegistrationReport = sequelize.import('./definition/trading-history-p-p-s-r-registration-reports.js');
    model.TradingHistoryPreASICDocument = sequelize.import('./definition/trading-history-pre-a-s-i-c-documents.js');
    model.TradingHistoryPreviousCompanyAddress = sequelize.import('./definition/trading-history-previous-company-addresses.js');
    model.TradingHistoryPreviousCompanyShare = sequelize.import('./definition/trading-history-previous-company-shares.js');
    model.TradingHistoryPreviousDirectorDirectorshipMessage = sequelize.import('./definition/trading-history-previous-director-directorship-messages.js');
    model.TradingHistoryPreviousDirectorDirectorship = sequelize.import('./definition/trading-history-previous-director-directorships.js');
    model.TradingHistoryPreviousDirector = sequelize.import('./definition/trading-history-previous-directors.js');
    model.TradingHistoryPreviousIndividualShareHolder = sequelize.import('./definition/trading-history-previous-individual-share-holders.js');
    model.TradingHistoryPreviousName = sequelize.import('./definition/trading-history-previous-names.js');
    model.TradingHistoryPreviousOrganisationShareHolder = sequelize.import('./definition/trading-history-previous-organisation-share-holders.js');
    model.TradingHistoryPreviousOtherOfficer = sequelize.import('./definition/trading-history-previous-other-officers.js');
    model.TradingHistoryPreviousOtherOrganisationOfficer = sequelize.import('./definition/trading-history-previous-other-organisation-officers.js');
    model.TradingHistoryPreviousSecretary = sequelize.import('./definition/trading-history-previous-secretaries.js');
    model.TradingHistoryProprietorshipMessage = sequelize.import('./definition/trading-history-proprietorship-messages.js');
    model.TradingHistoryProprietorship = sequelize.import('./definition/trading-history-proprietorships.js');
    model.TradingHistoryScoreContributingFactor = sequelize.import('./definition/trading-history-score-contributing-factors.js');
    model.TradingHistoryScoreError = sequelize.import('./definition/trading-history-score-errors.js');
    model.TradingHistoryScoreWarning = sequelize.import('./definition/trading-history-score-warnings.js');
    model.TradingHistorySecretary = sequelize.import('./definition/trading-history-secretaries.js');
    model.TradingHistorySummaryEntry = sequelize.import('./definition/trading-history-summary-entries.js');
    model.TraxDocumentGeneration = sequelize.import('./definition/trax-document-generation.js');
    model.TraxTreeTriggerValidationSuite = sequelize.import('./definition/trax-tree-trigger-validation-suite.js');
    model.TraxTreeValidationFacet = sequelize.import('./definition/trax-tree-validation-facet.js');
    model.TraxTreeValidationFacetType = sequelize.import('./definition/trax-tree-validation-facet-type.js');
    model.TraxTreeValidationOutcome = sequelize.import('./definition/trax-tree-validation-outcome.js');
    model.TraxTreeValidationPlugin = sequelize.import('./definition/trax-tree-validation-plugin.js');
    model.TraxTreeValidationResult = sequelize.import('./definition/trax-tree-validation-result.js');
    model.TraxTreeValidationSource = sequelize.import('./definition/trax-tree-validation-source.js');
    model.TraxTreeValidationSuite = sequelize.import('./definition/trax-tree-validation-suite.js');
    model.TraxTreeValidationSuitePlugin = sequelize.import('./definition/trax-tree-validation-suite-plugin.js');
    model.Trigger = sequelize.import('./definition/trigger.js');
    model.TriggerAction = sequelize.import('./definition/trigger-action.js');
    model.TriggerActionParameter = sequelize.import('./definition/trigger-action-parameter.js');
    model.TriggerParameter = sequelize.import('./definition/trigger-parameter.js');
    model.TriggerPoint = sequelize.import('./definition/trigger-point.js');
    model.TriggerPointConditionStageType = sequelize.import('./definition/trigger-point-condition-stage-type.js');
    model.UltracsClient = sequelize.import('./definition/ultracs-client.js');
    model.V8archiveWorkbookvaluehistoryarchive = sequelize.import('./definition/v8archive--workbook-value-history-archive.js');
    model.V8archiveWorkbookvaluehistoryarchivesequenceview = sequelize.import('./definition/v8archive--workbook-value-history-archive-sequence-view.js');
    model.Valuation = sequelize.import('./definition/valuation.js');
    model.ValuationOrder = sequelize.import('./definition/valuation-order.js');
    model.ValuationOrderType = sequelize.import('./definition/valuation-order-type.js');
    model.ValuationPropertyType = sequelize.import('./definition/valuation-property-type.js');
    model.ValuationReport = sequelize.import('./definition/valuation-report.js');
    model.ValuationReportAddress = sequelize.import('./definition/valuation-report-address.js');
    model.ValuationReportBuildingType = sequelize.import('./definition/valuation-report-building-type.js');
    model.ValuationReportConditionType = sequelize.import('./definition/valuation-report-condition-type.js');
    model.ValuationReportCurrentUseType = sequelize.import('./definition/valuation-report-current-use-type.js');
    model.ValuationReportDatum = sequelize.import('./definition/valuation-report-data.js');
    model.ValuationReportPropertyInterestType = sequelize.import('./definition/valuation-report-property-interest-type.js');
    model.ValuationReportRelatedPartyRelationship = sequelize.import('./definition/valuation-report-related-party-relationship.js');
    model.ValuationReportRelatedPartyType = sequelize.import('./definition/valuation-report-related-party-type.js');
    model.ValuationReportTitleTenureType = sequelize.import('./definition/valuation-report-title-tenure-type.js');
    model.ValuationReportValuationSubType = sequelize.import('./definition/valuation-report-valuation-sub-type.js');
    model.ValuationRisk = sequelize.import('./definition/valuation-risk.js');
    model.ValuationTierType = sequelize.import('./definition/valuation-tier-type.js');
    model.ValuationType = sequelize.import('./definition/valuation-type.js');
    model.Workbook = sequelize.import('./definition/workbook.js');
    model.WorkbookHistory = sequelize.import('./definition/workbook-history.js');
    model.WorkbookParameter = sequelize.import('./definition/workbook-parameter.js');
    model.WorkbookParameterDirectionType = sequelize.import('./definition/workbook-parameter-direction-type.js');
    model.WorkbookParameterObjectType = sequelize.import('./definition/workbook-parameter-object-type.js');
    model.WorkbookParameterRelationship = sequelize.import('./definition/workbook-parameter-relationship.js');
    model.WorkbookParameterType = sequelize.import('./definition/workbook-parameter-type.js');
    model.WorkbookRuleCategory = sequelize.import('./definition/workbook-rule-category.js');
    model.WorkbookRuleOverrideValue = sequelize.import('./definition/workbook-rule-override-value.js');
    model.WorkbookRuleType = sequelize.import('./definition/workbook-rule-type.js');
    model.WorkbookValueHistory = sequelize.import('./definition/workbook-value-history.js');
    model.WorkbookValueHistoryArchive = sequelize.import('./definition/workbook-value-history-archive.js');
    model.ZoningType = sequelize.import('./definition/zoning-type.js');

    // All models are initialized. Now connect them with relations.
    require('./definition/a-a-a-temp.js').initRelations();
    require('./definition/accessory-category-product-category-accessory-type.js').initRelations();
    require('./definition/accessory-category-type.js').initRelations();
    require('./definition/accessory-category-type-product-category.js').initRelations();
    require('./definition/accessory-type.js').initRelations();
    require('./definition/application-condition.js').initRelations();
    require('./definition/application-container.js').initRelations();
    require('./definition/application-container-fee.js').initRelations();
    require('./definition/application-equipment-program-product-pricing-link.js').initRelations();
    require('./definition/application-equipment-security-address-link.js').initRelations();
    require('./definition/application-history.js').initRelations();
    require('./definition/application-history-publication-type.js').initRelations();
    require('./definition/application-history-sequence-view.js').initRelations();
    require('./definition/application-history-type.js').initRelations();
    require('./definition/application-history-type-category.js').initRelations();
    require('./definition/application-l-v-r.js').initRelations();
    require('./definition/application-motor-program-product-pricing-link.js').initRelations();
    require('./definition/application-motor-vehicle-security-registration-state.js').initRelations();
    require('./definition/application-party-role.js').initRelations();
    require('./definition/application-party-role-ancillary.js').initRelations();
    require('./definition/application-party-role-employment-contacts.js').initRelations();
    require('./definition/application-party-role-household.js').initRelations();
    require('./definition/application-party-role-identity.js').initRelations();
    require('./definition/application-party-role-relationship.js').initRelations();
    require('./definition/application-party-role-relationship-type.js').initRelations();
    require('./definition/application-party-role-relationship-type-party-type.js').initRelations();
    require('./definition/application-party-role-sequence-view.js').initRelations();
    require('./definition/application-party-role-type.js').initRelations();
    require('./definition/application-security.js').initRelations();
    require('./definition/application-security-outgoing-finance.js').initRelations();
    require('./definition/application-security-purpose-type.js').initRelations();
    require('./definition/application-serviceability-history.js').initRelations();
    require('./definition/application-serviceability-history-value.js').initRelations();
    require('./definition/application-stage-type.js').initRelations();
    require('./definition/application-stage-type-application-status-type.js').initRelations();
    require('./definition/application-status-category-type.js').initRelations();
    require('./definition/application-status-history.js').initRelations();
    require('./definition/application-status-rollback-job-type.js').initRelations();
    require('./definition/application-status-trax-job.js').initRelations();
    require('./definition/application-status-type.js').initRelations();
    require('./definition/application-status-type-product-category.js').initRelations();
    require('./definition/application-status-type-product-category-crash-reason-type.js').initRelations();
    require('./definition/application-status-type-product-category-link-order.js').initRelations();
    require('./definition/application-supplier-crumbs-party-role.js').initRelations();
    require('./definition/application-type.js').initRelations();
    require('./definition/application-valuation-order-type.js').initRelations();
    require('./definition/asset.js').initRelations();
    require('./definition/asset-type.js').initRelations();
    require('./definition/auto-assessment-policy-owner.js').initRelations();
    require('./definition/auto-assessment-policy-type.js').initRelations();
    require('./definition/auto-assessment-product-category-policy-type-rule-type.js').initRelations();
    require('./definition/auto-assessment-rule-type.js').initRelations();
    require('./definition/auto-assessment-rule-value.js').initRelations();
    require('./definition/automated-valuation-model-detail.js').initRelations();
    require('./definition/condition-auto-verification-status-type.js').initRelations();
    require('./definition/condition-category-type.js').initRelations();
    require('./definition/condition-display-type.js').initRelations();
    require('./definition/condition-level-type.js').initRelations();
    require('./definition/condition-stage-category-type.js').initRelations();
    require('./definition/condition-type.js').initRelations();
    require('./definition/condition-type-configuration.js').initRelations();
    require('./definition/condition-type-configuration-application-status-type.js').initRelations();
    require('./definition/condition-type-configuration-relationship.js').initRelations();
    require('./definition/condition-type-configuration-trax-job-type.js').initRelations();
    require('./definition/condition-type-product-category.js').initRelations();
    require('./definition/condition-type-relationship-type.js').initRelations();
    require('./definition/condition-type-scanned-document-applies-to-type.js').initRelations();
    require('./definition/condition-verification-relationship-type.js').initRelations();
    require('./definition/condition-verification-status-type.js').initRelations();
    require('./definition/crash-reason-type.js').initRelations();
    require('./definition/credit-card-authority.js').initRelations();
    require('./definition/credit-card-process-history.js').initRelations();
    require('./definition/credit-card-type.js').initRelations();
    require('./definition/credit-report.js').initRelations();
    require('./definition/credit-report-account.js').initRelations();
    require('./definition/credit-report-address.js').initRelations();
    require('./definition/credit-report-association.js').initRelations();
    require('./definition/credit-report-business-name.js').initRelations();
    require('./definition/credit-report-court-action.js').initRelations();
    require('./definition/credit-report-credit-enquiry.js').initRelations();
    require('./definition/credit-report-default.js').initRelations();
    require('./definition/credit-report-directorship.js').initRelations();
    require('./definition/credit-report-disqualified-directorship.js').initRelations();
    require('./definition/credit-report-employment.js').initRelations();
    require('./definition/credit-report-file-note.js').initRelations();
    require('./definition/credit-report-identity.js').initRelations();
    require('./definition/credit-report-main.js').initRelations();
    require('./definition/credit-report-message.js').initRelations();
    require('./definition/credit-report-personal-insolvency.js').initRelations();
    require('./definition/credit-report-repayment-history.js').initRelations();
    require('./definition/credit-report-required.js').initRelations();
    require('./definition/credit-report-required-sequence-view.js').initRelations();
    require('./definition/credit-report-score-data-contributing-factor.js').initRelations();
    require('./definition/credit-report-summary-data.js').initRelations();
    require('./definition/credit-report-type.js').initRelations();
    require('./definition/crumbs--address.js').initRelations();
    require('./definition/crumbs--address-sequence-view.js').initRelations();
    require('./definition/crumbs--address-type.js').initRelations();
    require('./definition/crumbs--alignment-type.js').initRelations();
    require('./definition/crumbs--application-role.js').initRelations();
    require('./definition/crumbs--bank-account.js').initRelations();
    require('./definition/crumbs--bank-b-s-b.js').initRelations();
    require('./definition/crumbs--bank-b-s-b-sequence-view.js').initRelations();
    require('./definition/crumbs--brand.js').initRelations();
    require('./definition/crumbs--brand-text.js').initRelations();
    require('./definition/crumbs--broker-program-agreement.js').initRelations();
    require('./definition/crumbs--claim-type.js').initRelations();
    require('./definition/crumbs--claim-value.js').initRelations();
    require('./definition/crumbs--company.js').initRelations();
    require('./definition/crumbs--company-name-by-party-role.js').initRelations();
    require('./definition/crumbs--company-type.js').initRelations();
    require('./definition/crumbs--country.js').initRelations();
    require('./definition/crumbs--currency-type.js').initRelations();
    require('./definition/crumbs--document-location-type.js').initRelations();
    require('./definition/crumbs--email-address.js').initRelations();
    require('./definition/crumbs--email-address-sequence-view.js').initRelations();
    require('./definition/crumbs--equipment-finance-loan-application.js').initRelations();
    require('./definition/crumbs--firstmac-credit-score-history.js').initRelations();
    require('./definition/crumbs--firstmac-credit-score-type.js').initRelations();
    require('./definition/crumbs--gender-type.js').initRelations();
    require('./definition/crumbs--industry-type.js').initRelations();
    require('./definition/crumbs--location-type.js').initRelations();
    require('./definition/crumbs--login.js').initRelations();
    require('./definition/crumbs--login-claim-value-claim-type.js').initRelations();
    require('./definition/crumbs--marital-status-type.js').initRelations();
    require('./definition/crumbs--motor-vehicle-loan-application.js').initRelations();
    require('./definition/crumbs--object-colour-type.js').initRelations();
    require('./definition/crumbs--party.js').initRelations();
    require('./definition/crumbs--party-address.js').initRelations();
    require('./definition/crumbs--party-address-sequence-view.js').initRelations();
    require('./definition/crumbs--party-bank-account.js').initRelations();
    require('./definition/crumbs--party-bank-account-type.js').initRelations();
    require('./definition/crumbs--party-compliance.js').initRelations();
    require('./definition/crumbs--party-email.js').initRelations();
    require('./definition/crumbs--party-email-sequence-view.js').initRelations();
    require('./definition/crumbs--party-name-by-party-role-i-d.js').initRelations();
    require('./definition/crumbs--party-role.js').initRelations();
    require('./definition/crumbs--party-role-relationship.js').initRelations();
    require('./definition/crumbs--party-role-sequence-view.js').initRelations();
    require('./definition/crumbs--party-role-suite.js').initRelations();
    require('./definition/crumbs--party-role-type.js').initRelations();
    require('./definition/crumbs--party-score-history.js').initRelations();
    require('./definition/crumbs--party-score-history-sequence-view.js').initRelations();
    require('./definition/crumbs--party-sequence-view.js').initRelations();
    require('./definition/crumbs--party-telephone.js').initRelations();
    require('./definition/crumbs--party-telephone-sequence-view.js').initRelations();
    require('./definition/crumbs--party-trustee.js').initRelations();
    require('./definition/crumbs--party-type.js').initRelations();
    require('./definition/crumbs--permission-type.js').initRelations();
    require('./definition/crumbs--person.js').initRelations();
    require('./definition/crumbs--residency-type.js').initRelations();
    require('./definition/crumbs--role-type.js').initRelations();
    require('./definition/crumbs--role-type-permission-type.js').initRelations();
    require('./definition/crumbs--salutation-type.js').initRelations();
    require('./definition/crumbs--state.js').initRelations();
    require('./definition/crumbs--street-type.js').initRelations();
    require('./definition/crumbs--suburb.js').initRelations();
    require('./definition/crumbs--supplier-party-role-type-relationship.js').initRelations();
    require('./definition/crumbs--telephone-number.js').initRelations();
    require('./definition/crumbs--telephone-number-sequence-view.js').initRelations();
    require('./definition/crumbs--telephone-type.js').initRelations();
    require('./definition/crumbs--trust.js').initRelations();
    require('./definition/crumbs--trust-purpose-type.js').initRelations();
    require('./definition/crumbs--trust-structure-type.js').initRelations();
    require('./definition/currency-type.js').initRelations();
    require('./definition/deposit.js').initRelations();
    require('./definition/deposit-type.js').initRelations();
    require('./definition/direct-debit.js').initRelations();
    require('./definition/disbursement.js').initRelations();
    require('./definition/disbursement-draw-history.js').initRelations();
    require('./definition/disbursement-payment-type.js').initRelations();
    require('./definition/disbursement-sub-type.js').initRelations();
    require('./definition/disbursement-type.js').initRelations();
    require('./definition/disbursement-type-sub-type-option.js').initRelations();
    require('./definition/documentation-type.js').initRelations();
    require('./definition/documentcontrol--document-type.js').initRelations();
    require('./definition/documentcontrol--generation.js').initRelations();
    require('./definition/documentcontrol--generation-set.js').initRelations();
    require('./definition/documentcontrol--generation-set-item.js').initRelations();
    require('./definition/documentcontrol--template.js').initRelations();
    require('./definition/document-order-history.js').initRelations();
    require('./definition/document-order-history-application-party-role.js').initRelations();
    require('./definition/document-order-history-application-party-role-status.js').initRelations();
    require('./definition/document-order-history-application-party-role-viewer.js').initRelations();
    require('./definition/document-order-history-audit-event.js').initRelations();
    require('./definition/document-order-history-audit-event-data.js').initRelations();
    require('./definition/document-order-history-audit-key-type.js').initRelations();
    require('./definition/document-order-status-category.js').initRelations();
    require('./definition/document-order-status-history.js').initRelations();
    require('./definition/document-order-status-type.js').initRelations();
    require('./definition/document-pack-rule-type.js').initRelations();
    require('./definition/employment.js').initRelations();
    require('./definition/employment-basis-type.js').initRelations();
    require('./definition/employment-category-type.js').initRelations();
    require('./definition/employment-status-type.js').initRelations();
    require('./definition/employment-status-type-basis-type-relationship.js').initRelations();
    require('./definition/equipment-finance-loan-application.js').initRelations();
    require('./definition/equipment-finance-loan-application-invoice.js').initRelations();
    require('./definition/equipment-finance-security.js').initRelations();
    require('./definition/equipment-finance-security-serial-location.js').initRelations();
    require('./definition/equipment-finance-security-type.js').initRelations();
    require('./definition/fee-type.js').initRelations();
    require('./definition/fee-type-product-category.js').initRelations();
    require('./definition/final-approval-process-history.js').initRelations();
    require('./definition/final-approval-process-product-category-job-type.js').initRelations();
    require('./definition/final-approval-process-type.js').initRelations();
    require('./definition/final-approval-process-type-product-category-type.js').initRelations();
    require('./definition/frequency-type.js').initRelations();
    require('./definition/home-loan-application.js').initRelations();
    require('./definition/home-loan-application-additional.js').initRelations();
    require('./definition/home-loan-application-repayment-transfer.js').initRelations();
    require('./definition/home-loan-security.js').initRelations();
    require('./definition/home-loan-security-type.js').initRelations();
    require('./definition/household.js').initRelations();
    require('./definition/income.js').initRelations();
    require('./definition/income-additional.js').initRelations();
    require('./definition/income-additional-type.js').initRelations();
    require('./definition/income-employment.js').initRelations();
    require('./definition/income-source-type.js').initRelations();
    require('./definition/insurance.js').initRelations();
    require('./definition/insurance-type.js').initRelations();
    require('./definition/insurance-type-product-category.js').initRelations();
    require('./definition/invoice.js').initRelations();
    require('./definition/liability.js').initRelations();
    require('./definition/liability-category-type.js').initRelations();
    require('./definition/liability-type.js').initRelations();
    require('./definition/lite-history-import--temp.js').initRelations();
    require('./definition/loan.js').initRelations();
    require('./definition/loan-margin-history.js').initRelations();
    require('./definition/loan-m-d-r-history.js').initRelations();
    require('./definition/loan-program-product-history.js').initRelations();
    require('./definition/loan-purpose.js').initRelations();
    require('./definition/loan-purpose-group.js').initRelations();
    require('./definition/loan-purpose-type.js').initRelations();
    require('./definition/loan-purpose-type-product-category.js').initRelations();
    require('./definition/loan-purpose-type-trax-job-type.js').initRelations();
    require('./definition/loan-tracker-action-type.js').initRelations();
    require('./definition/loan-tracker-application-status-allowable-documents.js').initRelations();
    require('./definition/loan-tracker-condition-display-type.js').initRelations();
    require('./definition/loan-tracker-condition-verification-stage.js').initRelations();
    require('./definition/loan-tracker-document-requirement-type.js').initRelations();
    require('./definition/loan-tracker-document-upload-type.js').initRelations();
    require('./definition/loan-tracker-form.js').initRelations();
    require('./definition/loan-tracker-tool-tip.js').initRelations();
    require('./definition/loan-tracker-tool-tip-type.js').initRelations();
    require('./definition/loan-xref-history.js').initRelations();
    require('./definition/loan-xref-pool-history.js').initRelations();
    require('./definition/loan-xref-pool-history-status.js').initRelations();
    require('./definition/loan-xref-pool-history-status-level-type.js').initRelations();
    require('./definition/loan-xref-pool-history-status-type.js').initRelations();
    require('./definition/loan-xref-value.js').initRelations();
    require('./definition/loan-xref-value-type.js').initRelations();
    require('./definition/lot-type.js').initRelations();
    require('./definition/marital-status-type.js').initRelations();
    require('./definition/mortgage-type.js').initRelations();
    require('./definition/mortgagor.js').initRelations();
    require('./definition/motor-vehicle-loan-application.js').initRelations();
    require('./definition/motor-vehicle-loan-application-invoice.js').initRelations();
    require('./definition/motor-vehicle-rate-adjustment-history.js').initRelations();
    require('./definition/motor-vehicle-security.js').initRelations();
    require('./definition/motor-vehicle-security-type.js').initRelations();
    require('./definition/motor-vehicle-security-valuation.js').initRelations();
    require('./definition/occupancy-type.js').initRelations();
    require('./definition/party-role.js').initRelations();
    require('./definition/party-role-sequence-view.js').initRelations();
    require('./definition/personal-loan-application.js').initRelations();
    require('./definition/pms--balloon.js').initRelations();
    require('./definition/pms--equipment-finance-loan-product.js').initRelations();
    require('./definition/pms--equipment-finance-loan-program-product-pricing.js').initRelations();
    require('./definition/pms--equipment-finance-product-category.js').initRelations();
    require('./definition/pms--equipment-finance-product-type-frequency-type.js').initRelations();
    require('./definition/pms--frequency-type.js').initRelations();
    require('./definition/pms--funder-product.js').initRelations();
    require('./definition/pms--funder-product-cost-history.js').initRelations();
    require('./definition/pms--interest-type.js').initRelations();
    require('./definition/pms--motor-vehicle-loan-product.js').initRelations();
    require('./definition/pms--motor-vehicle-loan-program-product-pricing.js').initRelations();
    require('./definition/pms--product.js').initRelations();
    require('./definition/pms--program-product.js').initRelations();
    require('./definition/pms--program-product-information--by-program-product-pricing-i-d.js').initRelations();
    require('./definition/pms--term-type.js').initRelations();
    require('./definition/pool.js').initRelations();
    require('./definition/p-p-s-r-status-type.js').initRelations();
    require('./definition/premises-location-type.js').initRelations();
    require('./definition/product-category.js').initRelations();
    require('./definition/product-container.js').initRelations();
    require('./definition/quote.js').initRelations();
    require('./definition/quote-type.js').initRelations();
    require('./definition/rate-adjustment-reason-type.js').initRelations();
    require('./definition/repayment-amount-type.js').initRelations();
    require('./definition/repayment-method-type.js').initRelations();
    require('./definition/residency-type.js').initRelations();
    require('./definition/retail--customer.js').initRelations();
    require('./definition/retail--equipment-finance-loan-application.js').initRelations();
    require('./definition/retail--lead.js').initRelations();
    require('./definition/retail--lead-creation-source.js').initRelations();
    require('./definition/retail--lead-customer-relationship.js').initRelations();
    require('./definition/retail--lead-history.js').initRelations();
    require('./definition/retail--motor-vehicle-engine-type.js').initRelations();
    require('./definition/retail--motor-vehicle-loan-application.js').initRelations();
    require('./definition/retail--motor-vehicle-make.js').initRelations();
    require('./definition/retail--motor-vehicle-model.js').initRelations();
    require('./definition/retail--motor-vehicle-specification.js').initRelations();
    require('./definition/risk-description-type.js').initRelations();
    require('./definition/risk-rating-type.js').initRelations();
    require('./definition/risk-type.js').initRelations();
    require('./definition/security.js').initRelations();
    require('./definition/security-accessory.js').initRelations();
    require('./definition/security-encumbrance-type.js').initRelations();
    require('./definition/security-mortgage-registration.js').initRelations();
    require('./definition/security-p-p-s-r.js').initRelations();
    require('./definition/security-serial-location.js').initRelations();
    require('./definition/security-status-type.js').initRelations();
    require('./definition/security-title-dealing-type.js').initRelations();
    require('./definition/security-title-encumbrances.js').initRelations();
    require('./definition/security-title-insurance.js').initRelations();
    require('./definition/security-title-plan-type.js').initRelations();
    require('./definition/security-title-type.js').initRelations();
    require('./definition/security-type.js').initRelations();
    require('./definition/serviceability-calculator-version.js').initRelations();
    require('./definition/serviceability-history.js').initRelations();
    require('./definition/serviceability-value-history.js').initRelations();
    require('./definition/serviceability-value-type.js').initRelations();
    require('./definition/settlement.js').initRelations();
    require('./definition/settlement-category-type.js').initRelations();
    require('./definition/settlement-checkpoint.js').initRelations();
    require('./definition/settlement-checkpoint-illegal-current.js').initRelations();
    require('./definition/settlement-checkpoint-required-before.js').initRelations();
    require('./definition/settlement-checkpoint-type.js').initRelations();
    require('./definition/settlement-process-history.js').initRelations();
    require('./definition/settlement-process-history-settlements.js').initRelations();
    require('./definition/settlement-process-type.js').initRelations();
    require('./definition/settlement-type.js').initRelations();
    require('./definition/settlement-type-category-type-option.js').initRelations();
    require('./definition/sub-condition-level-type.js').initRelations();
    require('./definition/submission-source-type.js').initRelations();
    require('./definition/term-category.js').initRelations();
    require('./definition/term-type.js').initRelations();
    require('./definition/test-app-submission.js').initRelations();
    require('./definition/trading-history-aggregated-payment-reference.js').initRelations();
    require('./definition/trading-history-annual-returns.js').initRelations();
    require('./definition/trading-history-a-s-i-c-documents.js').initRelations();
    require('./definition/trading-history-broker-agent-enquiries.js').initRelations();
    require('./definition/trading-history-classification.js').initRelations();
    require('./definition/trading-history-company-director-address.js').initRelations();
    require('./definition/trading-history-company-director-employment.js').initRelations();
    require('./definition/trading-history-company-directors.js').initRelations();
    require('./definition/trading-history-court-judgements.js').initRelations();
    require('./definition/trading-history-court-writs.js').initRelations();
    require('./definition/trading-history-credit-enquiries.js').initRelations();
    require('./definition/trading-history-current-company-addresses.js').initRelations();
    require('./definition/trading-history-current-company-shares.js').initRelations();
    require('./definition/trading-history-deductible-gift-recipients.js').initRelations();
    require('./definition/trading-history-d-f-address.js').initRelations();
    require('./definition/trading-history-director-bankruptcies.js').initRelations();
    require('./definition/trading-history-director-broker-agent-enquiries.js').initRelations();
    require('./definition/trading-history-director-court-judgements.js').initRelations();
    require('./definition/trading-history-director-court-writs.js').initRelations();
    require('./definition/trading-history-director-credit-enquiries.js').initRelations();
    require('./definition/trading-history-director-credit-providers.js').initRelations();
    require('./definition/trading-history-director-cross-references.js').initRelations();
    require('./definition/trading-history-director-directorship-messages.js').initRelations();
    require('./definition/trading-history-director-directorships.js').initRelations();
    require('./definition/trading-history-director-disqualification-messages.js').initRelations();
    require('./definition/trading-history-director-disqualifications.js').initRelations();
    require('./definition/trading-history-director-faults.js').initRelations();
    require('./definition/trading-history-director-file-notes.js').initRelations();
    require('./definition/trading-history-director-legal-messages.js').initRelations();
    require('./definition/trading-history-director-payment-defaults.js').initRelations();
    require('./definition/trading-history-director-proprietorship-messages.js').initRelations();
    require('./definition/trading-history-director-proprietorships.js').initRelations();
    require('./definition/trading-history-directors.js').initRelations();
    require('./definition/trading-history-director-score.js').initRelations();
    require('./definition/trading-history-director-score-contributing-factors.js').initRelations();
    require('./definition/trading-history-director-score-errors.js').initRelations();
    require('./definition/trading-history-director-score-warnings.js').initRelations();
    require('./definition/trading-history-director-summary-entries.js').initRelations();
    require('./definition/trading-history-director-warning-meta-data.js').initRelations();
    require('./definition/trading-history-director-warnings.js').initRelations();
    require('./definition/trading-history-errors.js').initRelations();
    require('./definition/trading-history-external-administrators.js').initRelations();
    require('./definition/trading-history-file-notes.js').initRelations();
    require('./definition/trading-history-financial-reports.js').initRelations();
    require('./definition/trading-history-future-company-addresses.js').initRelations();
    require('./definition/trading-history-individual-share-holders.js').initRelations();
    require('./definition/trading-history-industry-days-beyond-term.js').initRelations();
    require('./definition/trading-history-industry-late-payment-days.js').initRelations();
    require('./definition/trading-history-industry-scores.js').initRelations();
    require('./definition/trading-history-industry-score-y-points.js').initRelations();
    require('./definition/trading-history-last200-payment-reference.js').initRelations();
    require('./definition/trading-history-legal-messages.js').initRelations();
    require('./definition/trading-history-main.js').initRelations();
    require('./definition/trading-history-market-late-payment-days.js').initRelations();
    require('./definition/trading-history-mercantile-enquiries.js').initRelations();
    require('./definition/trading-history-organisation-details.js').initRelations();
    require('./definition/trading-history-organisation-share-holders.js').initRelations();
    require('./definition/trading-history-other-entities.js').initRelations();
    require('./definition/trading-history-other-officers.js').initRelations();
    require('./definition/trading-history-other-organisation-officers.js').initRelations();
    require('./definition/trading-history-payment-defaults.js').initRelations();
    require('./definition/trading-history-payment-references-by-debt-size.js').initRelations();
    require('./definition/trading-history-payment-summary.js').initRelations();
    require('./definition/trading-history-petitions.js').initRelations();
    require('./definition/trading-history-p-p-s-r-commercial-collateral-class-summary.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-changes.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-collateral.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-collateral-attachments.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-details.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-detail-secured-parties.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-elements.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-element-secured-parties.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-grantors.js').initRelations();
    require('./definition/trading-history-p-p-s-r-registration-reports.js').initRelations();
    require('./definition/trading-history-pre-a-s-i-c-documents.js').initRelations();
    require('./definition/trading-history-previous-company-addresses.js').initRelations();
    require('./definition/trading-history-previous-company-shares.js').initRelations();
    require('./definition/trading-history-previous-director-directorship-messages.js').initRelations();
    require('./definition/trading-history-previous-director-directorships.js').initRelations();
    require('./definition/trading-history-previous-directors.js').initRelations();
    require('./definition/trading-history-previous-individual-share-holders.js').initRelations();
    require('./definition/trading-history-previous-names.js').initRelations();
    require('./definition/trading-history-previous-organisation-share-holders.js').initRelations();
    require('./definition/trading-history-previous-other-officers.js').initRelations();
    require('./definition/trading-history-previous-other-organisation-officers.js').initRelations();
    require('./definition/trading-history-previous-secretaries.js').initRelations();
    require('./definition/trading-history-proprietorship-messages.js').initRelations();
    require('./definition/trading-history-proprietorships.js').initRelations();
    require('./definition/trading-history-score-contributing-factors.js').initRelations();
    require('./definition/trading-history-score-errors.js').initRelations();
    require('./definition/trading-history-score-warnings.js').initRelations();
    require('./definition/trading-history-secretaries.js').initRelations();
    require('./definition/trading-history-summary-entries.js').initRelations();
    require('./definition/trax-document-generation.js').initRelations();
    require('./definition/trax-tree-trigger-validation-suite.js').initRelations();
    require('./definition/trax-tree-validation-facet.js').initRelations();
    require('./definition/trax-tree-validation-facet-type.js').initRelations();
    require('./definition/trax-tree-validation-outcome.js').initRelations();
    require('./definition/trax-tree-validation-plugin.js').initRelations();
    require('./definition/trax-tree-validation-result.js').initRelations();
    require('./definition/trax-tree-validation-source.js').initRelations();
    require('./definition/trax-tree-validation-suite.js').initRelations();
    require('./definition/trax-tree-validation-suite-plugin.js').initRelations();
    require('./definition/trigger.js').initRelations();
    require('./definition/trigger-action.js').initRelations();
    require('./definition/trigger-action-parameter.js').initRelations();
    require('./definition/trigger-parameter.js').initRelations();
    require('./definition/trigger-point.js').initRelations();
    require('./definition/trigger-point-condition-stage-type.js').initRelations();
    require('./definition/ultracs-client.js').initRelations();
    require('./definition/v8archive--workbook-value-history-archive.js').initRelations();
    require('./definition/v8archive--workbook-value-history-archive-sequence-view.js').initRelations();
    require('./definition/valuation.js').initRelations();
    require('./definition/valuation-order.js').initRelations();
    require('./definition/valuation-order-type.js').initRelations();
    require('./definition/valuation-property-type.js').initRelations();
    require('./definition/valuation-report.js').initRelations();
    require('./definition/valuation-report-address.js').initRelations();
    require('./definition/valuation-report-building-type.js').initRelations();
    require('./definition/valuation-report-condition-type.js').initRelations();
    require('./definition/valuation-report-current-use-type.js').initRelations();
    require('./definition/valuation-report-data.js').initRelations();
    require('./definition/valuation-report-property-interest-type.js').initRelations();
    require('./definition/valuation-report-related-party-relationship.js').initRelations();
    require('./definition/valuation-report-related-party-type.js').initRelations();
    require('./definition/valuation-report-title-tenure-type.js').initRelations();
    require('./definition/valuation-report-valuation-sub-type.js').initRelations();
    require('./definition/valuation-risk.js').initRelations();
    require('./definition/valuation-tier-type.js').initRelations();
    require('./definition/valuation-type.js').initRelations();
    require('./definition/workbook.js').initRelations();
    require('./definition/workbook-history.js').initRelations();
    require('./definition/workbook-parameter.js').initRelations();
    require('./definition/workbook-parameter-direction-type.js').initRelations();
    require('./definition/workbook-parameter-object-type.js').initRelations();
    require('./definition/workbook-parameter-relationship.js').initRelations();
    require('./definition/workbook-parameter-type.js').initRelations();
    require('./definition/workbook-rule-category.js').initRelations();
    require('./definition/workbook-rule-override-value.js').initRelations();
    require('./definition/workbook-rule-type.js').initRelations();
    require('./definition/workbook-value-history.js').initRelations();
    require('./definition/workbook-value-history-archive.js').initRelations();
    require('./definition/zoning-type.js').initRelations();
    return model;
}

// Note: While using this module, DO NOT FORGET FIRST CALL model.init(sequelize). Otherwise you get undefined.
module.exports = model;
module.exports.init = init;
module.exports.isInitialized = initialized;
